apiVersion: dstore.amber-store.io/v1alpha1
kind: DstoreCluster
metadata:
  name: demo
spec:
  nodes: 3
  replicationFactor: 3
  minReplicationFactor: 2
  image: ghcr.io/amber-store/dstore:v0.1.3
  capacityGiB: 100
  port: 4433
  hostNetwork: true
  gcInterval: 4h
  storage:
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
